#!/bin/bash

# this script needs to be run as user
MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $MYDIR/auto-video-ingest.cfg

function log {
	DATE=$(date "+%Y-%m-%d %H:%M:%S")
	echo "$DATE $1" >>$LOGFILE
	notify-send "auto-video-ingest" "$1"
}

log "Auto-video-ingest called for device $DEVICE"

# this is only required for the stupid usb readers which are slow. and those are
# only required because the intel nuc can not read one sandisk... thanks obama
START=$(date +%s)
for try in {1..50} ; do
	MOUNTPOINT=$(findmnt --source $DEVICE --output TARGET --noheadings)
    [[ ! -z "$MOUNTPOINT" ]] && break
	sleep .2
done
DURATION=$(( $(date +%s) - $START ))

if [ -z "$MOUNTPOINT" ];
then
	log "No mount point for SD card $DEVICE found after 10 seconds. Exiting"
	exit 0
else
	log "Mount for SD card $DEVICE found on $MOUNTPOINT after $DURATION seconds"
fi

# Checking if SD card is configured for auto-video-ingest
if [ ! -f $MOUNTPOINT/auto-video-ingest.cfg ];
then
	log "Not auto-video-ingest configured SD card. Exiting and ignoring it."
	exit 0
else
	source $MOUNTPOINT/auto-video-ingest.cfg
fi

# Checking if SD card configuration is valid
if [ -z "$NAME" ];
then
	log "auto-video-ingest cfg NAME not set. Exiting..."
	exit 0
fi
if [ -z "$SRCDIRS" ];
then
	log "auto-video-ingest cfg SRCDIRS not set. Exiting..."
	exit 0
fi
if [ -z "$EXCLUDES" ];
then
	log "auto-video-ingest cfg EXCLUDES not set."
fi
if [ -z "$SUBFOLDER" ];
then
	log "auto-video-ingest cfg SUBFOLDER not set. Exiting..."
	exit 0
fi

# ensure mounted NAS
if [ -z "$(mount | grep $TARGET)" ];
then
	log "NAS not mounted on $TARGET. Exiting"
	exit 1
fi

# creating definitive target directory variable
TARGETDIR=Media/$SUBFOLDER/$(date +%Y)/$(date +%Y-%m-%d)

# creating target dir
mkdir -p "$TARGET/$TARGETDIR/$NAME"
if [ ! -d "$TARGET/$TARGETDIR/$NAME" ];
then
	log "Unable to create target directory. Exiting"
	exit 1
fi

# doing the actual move and cleanup
log "Moving files to $TARGET/$TARGETDIR/$NAME"

# making sure the excludes file is empty
truncate -s 0 /tmp/auto-video-ingest.excludes
for EXCLUDE in $EXCLUDES;
do
	echo "$EXCLUDE" >>/tmp/auto-video-ingest.excludes
done

MOVE_START=$(date +%s)
for LOOPSRCDIR in $SRCDIRS;
do
	rsync -r --backup --suffix="_$(date +%H-%M-%S)" --remove-source-files --log-file=$LOGFILE --exclude-from=/tmp/auto-video-ingest.excludes "$MOUNTPOINT/$LOOPSRCDIR/" "$TARGET/$TARGETDIR/$NAME"
done
MOVE_FINISHED=$(date +%s)
rm /tmp/auto-video-ingest.excludes
log "File moving finished after $(( $MOVE_FINISHED - $MOVE_START )) seconds. Unmounting SD card."
sync
umount $MOUNTPOINT
