#!/bin/bash

# this script needs to be run as user
MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $MYDIR/auto-video-ingest.cfg

# since ubuntu seems to deactivate the required mount, we will set it at every startup
/usr/bin/gsettings set org.gnome.desktop.media-handling automount true

PIDFILE=/tmp/auto-video-ingest-watchdog.pid
if [ -f $PIDFILE ];
then
	echo "Watchdog already running! Exiting"
	exit 1
else
	echo $$ > $PIDFILE
	trap "rm -f $PIDFILE" EXIT
fi

function log {
	DATE=$(date "+%Y-%m-%d %H:%M:%S")
	echo "$DATE $1" >>$LOGFILE
}

# cleaning stale triggers
rm /tmp/auto-video-ingest.trigger >/dev/null 2>&1

# beginning to loop
log "Watchdog begins to watch for bones"

while true;
do
	if [ -f /tmp/auto-video-ingest.trigger ];
	then
		log "Watchdog found a bone in /tmp/auto-video-ingest.trigger."
		sleep 1
		cat /tmp/auto-video-ingest.trigger | while read line || [[ -n $device ]];
		do
			DEVICE=/dev/$device /bin/bash $MYDIR/auto-video-ingest
		done
		rm /tmp/auto-video-ingest.trigger
	fi
	sleep 1
done
