#!/bin/bash

# this script will to be run as root and has no permissions what so ever.
# just don't try to log anything, it won't work.
MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $MYDIR/auto-video-ingest.cfg

echo "$1" >/tmp/auto-video-ingest.trigger_tmp
/usr/bin/install -m 666 -o $DESKTOP_USER -g $DESKTOP_USER /tmp/auto-video-ingest.trigger_tmp /tmp/auto-video-ingest.trigger.$1
rm /tmp/auto-video-ingest.trigger_tmp
